version: '3'

tasks:
  cleanup:
    desc: Clean up the kubernetes cluster
    cmds:
      - cmd: |
          limactl stop {{.ITEM}} || true
          limactl delete {{.ITEM}} || true
        for: [jumpbox, server, node-0, node-1]
