version: '3'

dotenv: ['.env']

includes:
  00: ./tasks/00-setup-init
  01: ./tasks/01-prerequisites
  02: ./tasks/02-jumpbox
  03: ./tasks/03-compute-resources
  04: ./tasks/04-certificate-authority
  05: ./tasks/05-kubernetes-configuration-files
  06: ./tasks/06-data-encryption-keys
  07: ./tasks/07-bootstrapping-etcd
  08: ./tasks/08-bootstrapping-kubernetes-controllers
  09: ./tasks/09-bootstrapping-kubernetes-workers
  10: ./tasks/10-configuring-kubectl
  11: ./tasks/11-pod-network-routes
  12: ./tasks/12-smoke-test
  13: ./tasks/13-cleanup

tasks:
  setup-cluster:
    desc: Setup the Kubernetes cluster
    cmds:
      - task: 00:create-dotenv
      - task: 01:create-all
      - task: 02:setup-jumpbox
      - task: 03:configure-hostnames
      - task: 03:create-machines-txt-and-distribute-to-jumpbox
      - task: 03:verify-connectivities
      - task: 03:configure-ssh-access-from-jumpbox
      - task: 04:create-certificates
      - task: 04:distribute-certificates
      - task: 05:configure-cluster-access-for-jumpbox
      - task: 05:distribute-config-files-from-jumpbox
      - task: 06:generate-data-encryption-config-and-key
      - task: 07:copy-etcd-files-to-server
      - task: 07:bootstrap-etcd-cluster
      - task: 07:verify-etcd
      - task: 08:copy-k8s-binaries-to-server
      - task: 08:provision-control-plane
      - task: 08:verify-control-plane
      - task: 09:copy-k8s-binaries-to-nodes
      - task: 09:provision-k8s-nodes
      - task: 09:verify-k8s-nodes
      - task: 10:admin-kubeconfig
      - task: 10:verify-kubectl
      - task: 11:setup-pod-network-routes
      - task: 11:verify-pod-network-routes

  smoke-test:
    desc: Perform the smoke test to verify Kubernetes cluster functionality
    cmds:
      - task: 12:smoke-test

  clean-cluster:
    desc: Clean up the Kubernetes cluster
    cmds:
      - task: 13:cleanup
