version: '3'

dotenv: ['.env']

includes:
  00: ./tasks/00-setup-init
  01: ./tasks/01-prerequisites
  02: ./tasks/02-jumpbox
  03: ./tasks/03-compute-resources
  04: ./tasks/04-certificate-authority
  05: ./tasks/05-kubernetes-configuration-files
  06: ./tasks/06-data-encryption-keys
  07: ./tasks/07-bootstrapping-etcd
  08: ./tasks/08-bootstrapping-kubernetes-controllers

tasks:
  99:up-cluster:
    desc: Setup the kubernetes cluster
    cmds:
      - task: 00:create-dotenv
      - task: 00:download-docs
      - task: 01:create-all
      - task: 02:setup-jumpbox
      - task: 03:configure-hostnames
      - task: 03:verify-connectivities
      - task: 03:configure-ssh-access-from-jumpbox
      - task: 04:create-certificates
      - task: 04:distribute-certificates
      - task: 05:configure-cluster-access-for-jumpbox
      - task: 05:distribute-config-files-from-jumpbox
      - task: 06:generate-data-encryption-config-and-key
      - task: 07:copy-etcd-files-to-server
      - task: 07:bootstrap-etcd-cluster
      - task: 07:verify-etcd
      - task: 08:copy-k8s-binaries-to-server
      - task: 08:provision-control-plane
      - task: 08:verify-control-plane

  99:clean-cluster:
    desc: Clean up the kubernetes cluster
    cmds:
      - task: 01:delete-all
