version: '3'

tasks:
  clone-repo:
    desc: Clone the kubernetes-the-hard-way repository into the project directory
    cmds:
      - git clone git@github.com:kelseyhightower/kubernetes-the-hard-way.git

  create-all:
    desc: Start all machines using Lima
    cmds:
      - NAME=jumpbox task create
      - NAME=server task create
      - NAME=node-0 task create
      - NAME=node-1 task create
  create:
    desc: Create a Lima instance with a template
    cmds:
      - limactl start --name={{.NAME}} lima/{{.NAME}}/{{.NAME}}.yaml
    vars:
      NAME:
        sh: echo "${NAME:-missing}"

  validate-all:
    desc: Validate all machine configurations using Lima
    cmds:
      - NAME=jumpbox task validate
      - NAME=server task validate
      - NAME=node-0 task validate
      - NAME=node-1 task validate
  validate:
    desc: Validate a Lima instance configuration
    cmds:
      - limactl validate lima/{{.NAME}}/{{.NAME}}.yaml
    vars:
      NAME:
        sh: echo "${NAME:-missing}"
  
  recreate-all:
    desc: Recreate all machines using Lima
    cmds:
      - NAME=jumpbox task recreate
      - NAME=server task recreate
      - NAME=node-0 task recreate
      - NAME=node-1 task recreate
  recreate:
    desc: Recreate a Lima instance with updated template
    cmds:
      - limactl stop {{.NAME}} || true
      - limactl delete {{.NAME}} || true
      - limactl start --name={{.NAME}} lima/{{.NAME}}/{{.NAME}}.yaml
    vars:
      NAME:
        sh: echo "${NAME:-missing}"
