version: '3'

tasks:
  clone-repo:
    desc: Clone the kubernetes-the-hard-way repository into the project directory
    cmds:
      - git clone git@github.com:kelseyhightower/kubernetes-the-hard-way.git
