version: '3'

tasks:
  setup-pod-network-routes:
    desc: Setup Pod network routes for Kubernetes nodes
    vars:
      SERVER_IP:
        sh: awk '/server/ {print $1}' machines.txt
      NODE_0_IP:
        sh: awk '/node-0/ {print $1}' machines.txt
      NODE_0_SUBNET:
        sh: awk '/node-0/ {print $4}' machines.txt
      NODE_1_IP:
        sh: awk '/node-1/ {print $1}' machines.txt
      NODE_1_SUBNET:
        sh: awk '/node-1/ {print $4}' machines.txt
    cmds:
      - |
        echo "Setting up Pod network routes..."
        limactl shell server sudo -i bash<<'EOF'
          ip route add {{.NODE_0_SUBNET}} via {{.NODE_0_IP}}
          ip route add {{.NODE_1_SUBNET}} via {{.NODE_1_IP}}
        EOF

        limactl shell node-0 sudo -i bash<<'EOF'
          ip route add {{.NODE_1_SUBNET}} via {{.NODE_1_IP}}
        EOF

        limactl shell node-1 sudo -i bash<<'EOF'
          ip route add {{.NODE_0_SUBNET}} via {{.NODE_0_IP}}
        EOF

  verify-pod-network-routes:
    desc: Verify Pod network routes for Kubernetes nodes
    cmds:
      - limactl shell server sudo -i bash -c "ip route | grep lima0"
      - limactl shell node-0 sudo -i bash -c "ip route | grep lima0"
      - limactl shell node-1 sudo -i bash -c "ip route | grep lima0"
