version: '3'

tasks:
  cmd:
    desc: Run a command in the jumpbox
    cmds:
      - |
        #!/bin/bash

        limactl shell {{.NAME}} sudo -i bash <<'EOF'
        cd {{.ROOT_DIR}}/lima/{{.NAME}}
        ./{{.CMD}}
        EOF
