version: '3'

tasks:
  cmd:
    internal: true
    desc: Run command in the specified environment
    cmds:
      - |
        #!/bin/bash

        limactl shell {{.NAME}} sudo -i bash <<'EOF'
        cd {{.ROOT_DIR}}/lima/{{.NAME}}
        ./{{.CMD}}
        EOF
