version: '3'

tasks:
  create-all:
    desc: Start all machines using Lima
    cmds:
      - task: create
        vars:
          NAME: '{{.ITEM}}'
          ROOT_DIR: '{{.ROOT_DIR}}'
        for: [jumpbox, server, node-0, node-1]
  create:
    desc: Create a Lima instance with a templ
    cmds:
      - limactl start --tty=false --name={{.NAME}} lima/{{.NAME}}/{{.NAME}}.yaml
      - task: export-bin-path-to-profile
        vars:
          NAME: '{{.NAME}}'
          ROOT_DIR: '{{.ROOT_DIR}}'
  export-bin-path-to-profile:
    internal: true
    desc: Add ~/bin path to shell profile inside Lima VM
    cmds:
      - |
        #!/bin/bash

        limactl shell {{.NAME}} sudo -i bash <<'EOF'
        BIN_PATH="{{.ROOT_DIR}}/lima/{{.NAME}}/bin"
        PROFILE_FILE="/root/.bashrc"

        echo "export PATH=\$PATH:$BIN_PATH" >> "$PROFILE_FILE"
        EOF

  validate-all:
    desc: Validate all machine configurations using Lima
    cmds:
      - task: validate
        vars:
          NAME: '{{.ITEM}}'
        for: [jumpbox, server, node-0, node-1]
  validate:
    desc: Validate a Lima instance configuration
    cmds:
      - limactl validate lima/{{.NAME}}/{{.NAME}}.yaml
  
  delete-all:
    desc: Delete all machines using Lima
    cmds:
      - task: delete
        vars:
          NAME: '{{.ITEM}}'
        for: [jumpbox, server, node-0, node-1]
  delete:
    desc: Delete a Lima instance
    cmds:
      - limactl stop {{.NAME}} || true
      - limactl delete {{.NAME}} || true

  recreate-all:
    desc: Recreate all machines using Lima
    cmds:
      - task: recreate
        vars:
          NAME: '{{.ITEM}}'
        for: [jumpbox, server, node-0, node-1]
  recreate:
    desc: Recreate a Lima instance with updated template
    cmds:
      - task: delete-all
      - task: create-all
  
  connect:
    desc: Connect to a VM as root user
    cmds:
      - limactl shell {{.NAME}} sudo -i
