version: '3'

tasks:
  clone-repo:
    desc: Clone the kubernetes-the-hard-way repository into the project directory
    cmds:
      - git clone git@github.com:kelseyhightower/kubernetes-the-hard-way.git

  create-all:
    desc: Start all machines using Lima
    cmds:
      - task: create
        vars:
          NAME: '{{.ITEM}}'
        for: [jumpbox, server, node-0, node-1]
  create:
    desc: Create a Lima instance with a template
    cmds:
      - limactl start --name={{.NAME}} lima/{{.NAME}}/{{.NAME}}.yaml

  validate-all:
    desc: Validate all machine configurations using Lima
    cmds:
      - task: validate
        vars:
          NAME: '{{.ITEM}}'
        for: [jumpbox, server, node-0, node-1]
  validate:
    desc: Validate a Lima instance configuration
    cmds:
      - limactl validate lima/{{.NAME}}/{{.NAME}}.yaml
  
  recreate-all:
    desc: Recreate all machines using Lima
    cmds:
      - task: recreate
        vars:
          NAME: '{{.ITEM}}'
        for: [jumpbox, server, node-0, node-1]
  recreate:
    desc: Recreate a Lima instance with updated template
    cmds:
      - limactl stop {{.NAME}} || true
      - limactl delete {{.NAME}} || true
      - limactl start --name={{.NAME}} lima/{{.NAME}}/{{.NAME}}.yaml
  
  connect:
    desc: Connect to a VM as root user
    cmds:
      - limactl shell {{.NAME}} sudo -i
  