version: '3'

tasks:
  create-dotenv:
    desc: Create a .env file with the current directory
    cmds:
      - |
        #!/bin/bash

        rm -f .env

        echo "ROOT_DIR=$(pwd)" > .env
        echo "ROOT_PASS=$(openssl rand -base64 12)" >> .env
