version: '3'

includes:
  utils: ../Taskfile.yml

tasks:
  setup-jumpbox:
    desc: Setup the jumpbox machine
    cmds:
      - task: utils:cmd
        vars:
          NAME: jumpbox
          CMD: 02-setup-jumpbox
