version: '3'

includes:
  utils: ../Taskfile.yml

tasks:
  setup-jumpbox:
    desc: Setup the jumpbox machine
    cmds:
      - task: utils:cmd
        vars:
          ROOT_DIR: '{{.ROOT_DIR}}'
          NAME: jumpbox
          CMD: setup-jumpbox
