version: '3'

tasks:
  setup-jumpbox:
    desc: Setup the jumpbox machine
    vars:
      ROOT_DIR: '{{.ROOT_DIR}}'
    cmds:
      - |
        #!/bin/bash

        limactl shell jumpbox sudo -i bash <<'EOF'
        cd {{.ROOT_DIR}}/lima/jumpbox
        ./setup-jumpbox.sh
        EOF
