version: '3'

includes:
  utils: ../Taskfile.yml

tasks:
  configure-cluster-access-for-jumpbox:
    desc: Configure the jumpbox machine to access the cluster
    cmds:
      - task: utils:cmd
        vars:
          ROOT_DIR: '{{.ROOT_DIR}}'
          NAME: jumpbox
          CMD: configure-cluster-access
  
  distribute-config-files-from-jumpbox:
    desc: Distribute the Kubernetes configuration files from the jumpbox machine to the cluster nodes
    cmds:
      - task: utils:cmd
        vars:
          ROOT_DIR: '{{.ROOT_DIR}}'
          NAME: jumpbox
          CMD: distribute-config-files
