version: '3'

includes:
  utils: ../Taskfile.yml

tasks:
  create-certificates:
    desc: Create the certificate authority and certificates for the cluster
    cmds:
      - task: utils:cmd
        vars:
          ROOT_DIR: '{{.ROOT_DIR}}'
          NAME: jumpbox
          CMD: create-certificates

  distribute-certificates:
    desc: Distribute the certificates to the machines
    cmds:
      - task: utils:cmd
        vars:
          ROOT_DIR: '{{.ROOT_DIR}}'
          NAME: jumpbox
          CMD: distribute-certificates
